var mobilemode=false;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){var mobilemode=true;}
jQuery(document).ready(function($){if($('.post-content.cust_cont ul').length){$('.post-content.cust_cont ul li a').click(function(event){var divid=$(this).attr('href');if(typeof divid!='undefined'&&divid&&$(divid).length){$('html, body').animate({scrollTop:$(divid).offset().top-110},'slow');return false;}});}
jQuery("#hb-blog-cta-top").insertAfter(jQuery(".post-content p:nth-child(4)"));jQuery("#menusocial").on("click",function(){if(jQuery("#menusocial").hasClass("menu--social")){jQuery(this).removeClass('menu--social');}else{jQuery(this).addClass('menu--social');}
if(jQuery(".m-navigation").hasClass("open-menu")){jQuery('.m-navigation').animate({width:'toggle'}).toggleClass('open-menu');jQuery('.full-bg-nav-opecity').removeClass('full-bg-nav-active')}});$(document).on("click",'.navbar-toggle',function(){if(jQuery("#menusocial").hasClass("menu--social")){jQuery("#menusocial").removeClass('menu--social');}
jQuery('.m-navigation').animate({width:'toggle'}).toggleClass('open-menu');jQuery('.full-bg-nav-opecity').toggleClass('full-bg-nav-active');jQuery('body').toggleClass('body-scroll-h');});sidebar_slide_init();setTimeout(function(){(function(){var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];s1.async=true;s1.src='https://embed.tawk.to/56e185e25b6022b35f11920d/default';s1.charset='UTF-8';s1.setAttribute('crossorigin','*');s0.parentNode.insertBefore(s1,s0);})();},2000);$('#humburger-menu').click(function(){$(this).toggleClass('open');$(".topnavigation").toggleClass('menu-open');});var phplivechat_tracking=parseInt('');$(document).on("click",".phplive_btn_1453967008",function(){if(phplivechat_tracking){phplive_launch_chat_1(0);}else{toggleTawkChat();}});if($(".live-chat-pop-up-cls-dyn-spn").length>0){if(!phplivechat_tracking){$(".live-chat-pop-up-cls-dyn-spn").html('<img src="'+JS_TOP_LIVE_CAHT_LINK+'" class="live-chat-pop-up-cls" style="cursor:pointer;vertical-align:bottom" alt="" width="36" height="73" />');}}
setTimeout(function(){$('h3').attr('style','');$('h3').addClass('h3_class');$('h4').attr('style','');$('h4').addClass('h4_class');},500);});function sidebar_slide_init(){var width=jQuery(window).width();var $sidebar=jQuery('.content-column-sidebar');var $content=jQuery('.content-column-content');var menu_fixed=jQuery('body').hasClass('menu-position-top_fixed');var admin_bar=jQuery('body').hasClass('admin-bar');if(menu_fixed)
var $top_area=jQuery('.menu-sticky-node');var move_delay=1200;if($sidebar.data('move-delay')||$sidebar.data('move-delay')=='0'){var tmp=parseInt($sidebar.data('move-delay'));if(!isNaN(tmp))
move_delay=tmp;}
if($sidebar.length&&width>=768){$sidebar.mouseenter(function(){$sidebar.addClass('hovered');}).mouseleave(function(){$sidebar.removeClass('hovered');});var sidebar_timer=false;jQuery(window).scroll(function(){if(sidebar_timer)
clearTimeout(sidebar_timer);if(jQuery(window).data('mobile-view')){$sidebar.stop(true).css({marginTop:0,opacity:1});return;}
sidebar_timer=setTimeout(function(){$sidebar.stop(true);var ch=$content.height();var ws=jQuery(window).scrollTop();var wh=jQuery(window).height();var top=$sidebar.offset();var sidebarh=$sidebar.height();if(ch>sidebarh)
{var cur_mar=parseInt($sidebar.css('margin-top'));var max=ch-sidebarh;var new_mar=cur_mar;var gap=0;if(admin_bar)
gap+=32;if(menu_fixed&&$top_area.hasClass('menu-stuck')){gap+=$top_area.height();}
if(top.top-ws-gap>0){new_mar=ws-(top.top-cur_mar)+gap;if(new_mar>max)
new_mar=max;if(new_mar<0)
new_mar=0;}else if(top.top+sidebarh-ws-gap<wh){if(sidebarh<wh){new_mar=ws-(top.top-cur_mar)+gap;}else{new_mar=ws-(top.top-cur_mar)-(sidebarh-wh);}
if(new_mar>max)
new_mar=max;if(new_mar<0)
new_mar=0;}
if(new_mar!=cur_mar){$sidebar.fadeTo(600,0.2).fadeTo(400,1);$sidebar.animate({marginTop:new_mar+'px'},{duration:1000,easing:'easeInOutExpo',queue:false});}else{$sidebar.fadeTo(400,1);}}},move_delay);});}}
jQuery(window).scroll(function(){var scroll=jQuery(window).scrollTop();let limit=70;if(scroll>limit){jQuery("#hdr").addClass("sticky-hdr");}else{jQuery("#hdr").removeClass("sticky-hdr");}});function fling(){var btn=document.getElementById('fltBtn');var act=document.getElementsByClassName('action');if(btn==null){return;}
if(btn.children[0].className==='plus'){btn.children[0].className='plus textpand';btn.className='floating-btn boxspand';setTimeout(function(){act[0].className='action actionive';act[0].style.visibility="visible";},1);setTimeout(function(){act[1].className='action actionive';act[1].style.visibility="visible";},70);setTimeout(function(){act[2].className='action actionive';act[2].style.visibility="visible";},140);jQuery('.phplive_btn_1453967008').trigger('click');}else{btn.children[0].className='plus';btn.className='floating-btn';act[0].className='action';act[1].className='action';act[2].className='action';act[0].style.visibility="hidden";act[1].style.visibility="hidden";act[2].style.visibility="hidden";}}